version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev